### ISSUE TITLE
regarding code compatibility with OpenFoam-v1912

### ISSUE THREAD

**Issue by anuragray20** [hystrath/hyStrath#120]
Dear Dr. Vincent,
I have successfully compiled your hy2Foam with the OpenFoam-v1706 version. I now want to shift to the OpenFoam-v1912 version. How difficult it would be to compile your code in the 1912 version? Why the code is still compatible with the older version (1706) only? Is there any specific reason? Your valuable insights are needed as I am planning to make an attempt to shift the code to the 1912 version. 
Regards,
Anurag Ray

**Comment by vincentcasseau** [comment]
Please feel free to reopen this Issue if you have a specific question on the update. Thanks
